backend:
  name: git-gateway
  branch: main

media_folder: "src/assets"
public_folder: "/assets"

collections:
  - name: "posts"
    label: "Postovi"
    folder: "src/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Naslov", name: "title", widget: "string" }
      - { label: "Datum", name: "date", widget: "datetime" }
      - { label: "Kategorija", name: "category", widget: "string" }
      - { label: "Slika", name: "featured_image", widget: "image", required: false }
      - { label: "Sadr≈æaj", name: "body", widget: "markdown" }