backend:
  name: git-gateway
  branch: main

media_folder: "src/assets"
public_folder: "/assets"

collections:
  - name: "posts"
    label: "Postovi"
    folder: "src/posts"
    create: true
    slug: "{{slug}}"

    fields:
      - { label: "Layout", name: "layout", widget: "hidden", default: "post.njk" }

      - { label: "Naslov", name: "title", widget: "string" }

      - { label: "Datum", name: "date", widget: "datetime" }

      - label: "Razred"
        name: "category"
        widget: "select"
        options:
          - { label: "I razred", value: "i-razred" }
          - { label: "II razred", value: "ii-razred" }
          - { label: "III razred", value: "iii-razred" }
          - { label: "IV razred", value: "iv-razred" }

      - { label: "Slika", name: "featured_image", widget: "image", required: false }

      - { label: "Sadr≈æaj", name: "body", widget: "markdown" }